exclude: Doxyfile|libraries|Makefile|README|INSTALL|testpackage|doc|\.txt|\.tex|\.cfg|\.vtk|\.clang-format|\.m$|\.sh|\.py|\.dat|\.DAT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-tabs
        args: [--whitespaces-count, '8']
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        args: [-i]

ci:
    autofix_commit_msg: |
      automatic style and whitespace fixes
    autofix_prs: true
    autoupdate_branch: dev
